# 将静态内容部署到 GitHub Pages 的简单工作流程
名称：将静态内容部署到页面

在：
  针对默认分支的推送# 针对默认分支的推送
  推：推：推：推：
    修改：[ “主要” ]

  #投资者“操作者”指南手动运行此流程#
  活动调度：活动调度：

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
权限：
  内容： 内容：已读
  页数： 页数：写
  id 令牌    :       id-token： 写入

# 只允许一次发布，跳过发行运行和最新排队运行。
#但是，不要以为演出会成功，你只需要发布这些照片就可以了。
并发性：
  组：“页面”
  取消进行中: false

工作：
  # 由于我们只是部署，因此采用单一部署作业
  部署：
    环境：
名称：github-pages
      url  :       网址：$ {   {步骤.部署.输出.页面网址}     }      {      {步骤.部署.输出.页面网址}     }
    运行于： ubuntu-latest
    脚步：
      -名称:          - 名称：结帐
        用途： 用途：actions/checkout@v4
      -名称： - 名称：设置页面
        用途： 用途：actions/configure-pages@v5
      -名称:        - 名称：上传工件
        用途：actions/upload-pages-artifact@v3
        和：
          # 上传整个仓库
          小路：'。'
      -名称：部署到 GitHub Pages
        id：部署
        用途： actions/deploy-pages@v4
